sudo: false

matrix:
    include:
        - os: linux
          language: c
          compiler: gcc
          env:
              - VTK=5.10.1
              - PYTHON=2.7
          before_install:
              - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
              - chmod +x miniconda.sh
              - ./miniconda.sh -b -p $HOME/miniconda
              - export PATH=$HOME/miniconda/bin:$PATH
              - conda update --yes conda
              - conda create -n testenv --yes numpy scipy matplotlib pillow pyside vtk=$VTK pip nose setuptools python=$PYTHON
              - source activate testenv
        
        - os: linux
          language: c
          compiler: gcc
          env:
              - VTK=6.3.0
              - PYTHON=2.7
          before_install:
              - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
              - chmod +x miniconda.sh
              - ./miniconda.sh -b -p $HOME/miniconda
              - export PATH=$HOME/miniconda/bin:$PATH
              - conda update --yes conda
              - conda create -n testenv --yes numpy scipy matplotlib pillow pyside vtk=$VTK pip nose setuptools python=$PYTHON
              - source activate testenv
        
        - os: osx
          language: c
          compiler: gcc
          env:
              - VTK=5.10.1
              - PYTHON=2.7
          before_install:
              - wget http://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -O miniconda.sh
              - chmod +x miniconda.sh
              - ./miniconda.sh -b -p $HOME/miniconda
              - export PATH=$HOME/miniconda/bin:$PATH
              - export DYLD_LIBRARY_PATH=$HOME/miniconda/lib:$DYLD_LIBRARY_PATH
              - ls $HOME/miniconda
              - ls $HOME/miniconda/lib
              - conda update --yes conda
              - conda create -n testenv --yes numpy scipy matplotlib pillow pyside gcc vtk=$VTK pip nose setuptools python=$PYTHON
              - source activate testenv
        
        - os: osx
          language: c
          compiler: gcc
          env:
              - VTK=6.3.0
              - PYTHON=2.7
          before_install:
              - wget http://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -O miniconda.sh
              - chmod +x miniconda.sh
              - ./miniconda.sh -b -p $HOME/miniconda
              - export PATH=$HOME/miniconda/bin:$PATH
              - export DYLD_LIBRARY_PATH=$HOME/miniconda/lib:$DYLD_LIBRARY_PATH
              - conda update --yes conda
              - conda create -n testenv --yes numpy scipy matplotlib pillow pyside gcc vtk=$VTK pip nose setuptools python=$PYTHON
              - source activate testenv

install:
    - gcc --version
    - python --version
    - cp setup.cfg.example setup.cfg
    - python setup.py build_clib --compiler=unix
    - python setup.py build_ext --inplace --compiler=unix

before_script:
    - [ "${TRAVIS_OS_NAME}" -eq "linux" ] && export DISPLAY=:99.0" || true
    - [ "${TRAVIS_OS_NAME}" -eq "linux" ] && sh -e /etc/init.d/xvfb start || true
    - [ "${TRAVIS_OS_NAME}" -eq "linux" ] && sleep 3 || true

script:
    - python setup.py test
