sudo: false
language: c

matrix:
    include:
        - os: linux
          compiler: gcc
          env:
              - VTK=5.10.1
              - PYTHON=2.7
              - CONDAOS=Linux
        
        - os: linux
          compiler: gcc
          env:
              - VTK=6.3.0
              - PYTHON=2.7
              - CONDAOS=Linux
        
        - os: osx
          compiler: gcc
          env:
              - VTK=5.10.1
              - PYTHON=2.7
              - CONDAOS=MacOSX
        
        - os: osx
          compiler: gcc
          env:
              - VTK=6.3.0
              - PYTHON=2.7
              - CONDAOS=MacOSX

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-${CONDAOS}-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - if [ ${TRAVIS_OS_NAME} == "osx" ]; then export DYLD_LIBRARY_PATH=$HOME/miniconda/lib; fi
    - conda update --yes conda
    - conda create -n testenv --yes gcc numpy scipy matplotlib pillow pyside vtk=$VTK pip nose setuptools python=$PYTHON
    - source activate testenv
    - pip install pyhull
    - pip install pyinstaller

install:
    - echo $CC
    - gcc --version
    - python --version
    - cp setup.cfg.example setup.cfg
    - if [ ${TRAVIS_OS_NAME} == "linux" ]; then sed -i 's/#exclude = slowtests/exclude = slowtests/' setup.cfg; fi
    - CC=gcc CXX=g++ python setup.py build_clib --compiler=unix
    - CC=gcc CXX=g++ python setup.py build_ext --inplace --compiler=unix

script:
    - python setup.py test
