sudo: false
language: generic

matrix:
    include:
        - os: linux
          env:
              - VTK=5.10.1
              - PYTHON=2.7
              - CONDAOS=Linux
        
        - os: linux
          env:
              - VTK=6.3.0
              - PYTHON=2.7
              - CONDAOS=Linux
        
        - os: osx
          env:
              - VTK=5.10.1
              - PYTHON=2.7
              - CONDAOS=MacOSX
        
        - os: osx
          env:
              - VTK=6.3.0
              - PYTHON=2.7
              - CONDAOS=MacOSX

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-${CONDAOS}-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - if [ ${TRAVIS_OS_NAME} == "osx" ]; then brew update; brew outdated gcc || brew upgrade gcc; fi
    - if [ ${TRAVIS_OS_NAME} == "osx" ]; then export CC=gcc-5; export CXX=g++-5; fi
    - if [ ${TRAVIS_OS_NAME} == "linux" ]; then export CC=gcc; export CXX=g++; fi
    - echo $PATH
    - echo $DYLD_LIBRARY_PATH || true
    - conda update --yes conda
    - conda create -n testenv --yes numpy scipy matplotlib pillow vtk=$VTK pip nose setuptools sphinx python=$PYTHON
    - conda install --yes -n testenv -c https://conda.anaconda.org/dsdale24 qt5 pyqt5
    - source activate testenv
    - pip install sphinx_rtd_theme
    - pip install pyhull
    - pip install pyinstaller

install:
    - echo $CC
    - echo $CXX
    - $CC --version
    - $CXX --version
    - python --version
    - cp setup.cfg.example setup.cfg
    - if [ ${TRAVIS_OS_NAME} == "linux" ]; then sed -i 's/#exclude = slowtests/exclude = slowtests/' setup.cfg; fi
    - python setup.py --version
    - python setup.py build_clib
    - python setup.py build_ext --inplace
    - python setup.py build_sphinx

script:
    - python setup.py test
