sudo: false
language: c

matrix:
    include:
        - os: linux
          compiler: gcc
          env:
              - VTK=5.10.1
              - PYTHON=2.7
          before_install:
              - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
              - chmod +x miniconda.sh
              - ./miniconda.sh -b -p $HOME/miniconda
              - export PATH=$HOME/miniconda/bin:$PATH
              - conda update --yes conda
              - conda create -n testenv --yes numpy scipy matplotlib pillow pyside vtk=$VTK pip nose setuptools python=$PYTHON
              - source activate testenv
          before_script:
              - export DISPLAY=:99.0
              - sh -e /etc/init.d/xvfb start
              - sleep 3
        
        - os: linux
          compiler: gcc
          env:
              - VTK=6.3.0
              - PYTHON=2.7
          before_install:
              - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
              - chmod +x miniconda.sh
              - ./miniconda.sh -b -p $HOME/miniconda
              - export PATH=$HOME/miniconda/bin:$PATH
              - conda update --yes conda
              - conda create -n testenv --yes numpy scipy matplotlib pillow pyside vtk=$VTK pip nose setuptools python=$PYTHON
              - source activate testenv
          before_script:
              - export DISPLAY=:99.0
              - sh -e /etc/init.d/xvfb start
              - sleep 3
        
        - os: osx
          compiler: gcc
          env:
              - VTK=5.10.1
              - PYTHON=2.7
          before_install:
              - wget http://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -O miniconda.sh
              - chmod +x miniconda.sh
              - ./miniconda.sh -b -p $HOME/miniconda
              - export PATH=$HOME/miniconda/bin:$PATH
              - export DYLD_LIBRARY_PATH=$HOME/miniconda/lib:$DYLD_LIBRARY_PATH
              - ls $HOME/miniconda
              - ls $HOME/miniconda/lib
              - conda update --yes conda
              - conda create -n testenv --yes numpy scipy matplotlib pillow pyside gcc vtk=$VTK pip nose setuptools python=$PYTHON
              - source activate testenv
        
        - os: osx
          compiler: gcc
          env:
              - VTK=6.3.0
              - PYTHON=2.7
          before_install:
              - wget http://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -O miniconda.sh
              - chmod +x miniconda.sh
              - ./miniconda.sh -b -p $HOME/miniconda
              - export PATH=$HOME/miniconda/bin:$PATH
              - export DYLD_LIBRARY_PATH=$HOME/miniconda/lib:$DYLD_LIBRARY_PATH
              - conda update --yes conda
              - conda create -n testenv --yes numpy scipy matplotlib pillow pyside gcc vtk=$VTK pip nose setuptools python=$PYTHON
              - source activate testenv

install:
    - gcc --version
    - python --version
    - cp setup.cfg.example setup.cfg
    - python setup.py build_clib --compiler=unix
    - python setup.py build_ext --inplace --compiler=unix

script:
    - python setup.py test
